# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3e565b4aa68180cc7278fefac8b0522563cca14a9ab772a09ef3e6771b4d10ffcb45728d1c2d096d6f9802c2b7b2866f43a8e984f93ec123c0b44b89eec43c8

test:
  secret_key_base: 42fb9b4320f79a86d0d95cbb1593dcf78e26be6a78b7d563ccf10fd4c5d01621d90539e8aa9f086e5b3b96f0060ff99ddb8538489736493efa18c877bbb3cd2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
